- client/src/App.js
- server/config/database.js
- server/config/passport.js
- server/package-lock.json
- server/package.json
-Added databases and passport files to confiq folder, updated .env file. Added modules from quickpound format.
-Modules Added: cloundinary, connect-mongo, cookie-parser, dotenv, express, express-flash,  express-session, method-override, mongodb, morgan, multer, passport, passport-local, popups, validators 
-Check package.json folder under server side folder for the correct modules
-Check confiq folder in server side folder for files added
> Updating Folders and Merging

- client/src/components/IndividualFridge.js
**What I did:**
1. Create an IndividualFridge.js component to render individual fridges information (mockup attached below).
2. Hard code placeholder text so backend can replace it with data from mongo later (current rendering attached below).
3. You will also find that I installed a new dependency 'react-router-dom' in package.json because I wanted to figure out how to route to separate pages; however, I was unable to do that so I kept the IndividualFridge component on the landing page.
**Need to do:**
1. Eventually, we need to add Routes to frontend (link out to pages in nav bar) so pages like IndividualFridge component can be on its separate page.
2. Add images of the fridges as requested
**Questions:**
1. Do you want us to find and save images and put them in a file or is backend …
> created an Individual Fridge component with placeholder text

- server/controllers/fridge.js
- server/routes/fridge.js
- server/server.js
Added a landing for route requests in the server.js.
Also updated the name of the controller methos in the fridge.js controller to more accurately depict what the method does 
resolves #36
> resolves #36

- server/controllers/fridge.js
- server/routes/fridge.js
I added a controller for getting all fridges upon loading the page. FE will use this controller to automagically show all fridges in the city upon initial page load until a zipcode is specified. 
resolves #35 
***Not ready to test***
> add getAllFridges controller and route

- server/server.js
I changed the server folder server.js file to be in ES6 format 
check in the server.js file and confirm not imports that are missing are needed 
fixes #51 **This doesn't close the ticket. I still need to update files**
> updates server side server.js file to ES6 import/export format

- server/config/database.js
- server/controllers/fridge.js
- server/routes/fridge.js
- server/server.js
Added logic for a fridge.
Not ready for testing. Doesn't correspond to a ticket
> add logic to get a single fridge to display on fridge profile

- server/models/Comment.js
- server/models/CommunityFridge.js
- server/models/Post.js
- server/models/User.js
Changed all the Schemas to work with ES6 using ES6 standards
resolves #54 #61
> fixed schemas

- server/config/database.js
- server/config/passport.js
- server/controllers/fridge.js
- server/controllers/posts.js
- server/middleware/cloudinary.js
- server/models/CommunityFridge.js
- server/models/User.js
- server/package-lock.json
- server/package.json
- server/routes/fridge.js
- server/routes/posts.js
- server/server.js
Was debugging and realized almost all of the BE files need to be converted to ES6
Converted things to ES6 and removed uneccesary code. FE will be testing sooon
#63 
***not ready to test***
> cleaned up a bunch of code. converted stuff to es6

- .gitignore
> removed .env from gitignore so everyone can have access

- server/.env
> add .env to github

- client/package-lock.json
- client/package.json
fixed an error with react-router-dom
npm install react-router-dom for front end to work - was the solution so package.json got updated
> npm install react-router-dom for front end to work

- client/src/App.js
- client/src/pages/FridgeProfile.js
- server/server.js
What I did:
- after be connects to db, fe sends fetch to get data from db
- add cors error in be 
- talked to jacintha about cors error and touching backend, so we changed server port to 3000; now it's both 3000 on 3000
> connected fe to be db

- server/middleware/cloudinary.js
- server/middleware/multer.js
> change cloduindary link and path to cloudinary file

- server/controllers/auth.js
- server/controllers/profile.js
- server/models/User.js
- server/server.js
##What I did 
Updated the profile routes line in server.js
Fixed import for bcrpyt module 
run server in serverside and ensure no errors when trying to run server. Make sure to npm install!
errors we were getting: 
Fixed in this pull: 
For this error make sure your .env files on your local devices are outside of the config file to run the server and access the mongo string correctly:
> Fixes issue for module not importing for FE team

- client/src/App.css
- client/src/pages/FridgeProfile.js
- server/.env
1. Changed backend port back to 8000, because the client side (port 3000) can't make a request to the same port (previously 3000) --- CORS package re-imported
2. Added style and interactivity 
3. Added media queries
This is ready to merge to main
1. Some documents do not have food accepted / not accepted. To ensure consistency, please ask backend to put into the field "data does not exist" so it doesn't look like we forgot to pull data.
fixes #70 
fixes #72
> Fe stylized fridge pages

- client/src/App.css
- client/src/pages/FridgeProfile.js
- server/.env
1. Add conditional for if fridge status is Active to show green emoji; else if fridge status not Active it will show a red emoji
2. Add conditional for if there is no string in the donations section in database to display the else statement!
This can be pushed to main!
Closes #89
> Fe fridge conditionals

- server/controllers/posts.js
- server/middleware/cloundinary2.js
Kyle created a new cloundinary account to hold the images that are sent via posts made on the community board. 
##How to test
Once the community board is done, we would need to make a post to make sure that the photo is going to the correct cloudinary account. 
for now we can test by checking the files and the .env
> cloudinary created for posts

- client/src/components/CommunityFooter.js
- client/src/components/CommunityInvolvement.js
- client/src/components/MessageBoardInfo.js
- client/src/components/MessageBoardInteractive.js
- client/src/components/WelcomeCommunity.js
- client/src/pages/Community.js
- server/package.json
finished most of the community page. included a footer, header, nav, and fridge community post section styled very close to the figma. Still need to fix box next to Welcome to the Community Fridge. Also need to replace the image placeholders and grab them from cloudinary.
http://localhost:3000/Community?#
^ link to view it.
> Finished 90% of the community page frontend with the help of Anais -

- client/src/pages/Community.js
- client/src/pages/Home.js
What I did:
- added placeholders for the community board
How to test:
- cd to client, then npm start, then navigate to http://localhost:3000/community
> add community board placeholder

- client/src/App.css
- client/src/App.js
- client/src/pages/FridgeLanding.js
- client/src/pages/FridgeProfile.js
1. Dynamically render all fridges using getAllFridges CRUD from BE
2. Allow users to sort by zip code (in order), all fridges appear in alphabetical order
1. cd client / cd server - npm start on both since fe is making a req to be server to mongo
2. click learn more to see individual fridge pages
These pages are pretty much done.
> completed fridge menu styling and logic

- server/controllers/profile.js
I just updated the key names for some of the CRUD functionality
Run both servers and make sure you can make more than one user account
> updated username field and key names for mongo

- server/controllers/ourTeam.js
- server/controllers/posts.js
added a ourTeam.js controller file and fixed a variable in the post.js controller
#125
> BE team member controller added 

- client/src/components/Navbar.js
- client/src/pages/UserProfile.js
UI:
-User profile page layout includes two sections for changing contact information and changing the password.
-Each section contains a form with input fields and a "Save Changes" button.
-The input fields are controlled components, meaning their values are controlled by the component's state.
-Tailwind CSS classes used for styling the user interface components.
-The layout is responsive
-Added Navbar and Footer components
State Management using the useState hook:
-contactInfo: Manages form inputs related to contact information (first name, last name, email).
-passwordInfo: Manages form inputs related to password changes (old password, new password, confirm new password).
Event Handlers to update the state when input values change:
-handleContactInfoChange: Updates the contactInfo state …
> fe- wip add user profile with contact and password change

- client/src/components/AllPosts.js
- client/src/components/MessageBoardInteractive.js
- client/src/pages/Login.js
- client/src/pages/SignUp.js
- server/controllers/posts.js
- server/models/Post.js
- server/server.js
- Updated fetch request on FE communityboard interactive page to fetch from the correct links
- Fixed login and signup so that when a user logs in they stay logged in for their session
- Send session data from backend to frontend 
- Set up other input forms for data for posts that need to be received
- fixed photo submission on frontend to connect to backend
- updated secondary cloudinary info in personal file and in Nourish Links doc
- set up select inputs for fridge location and post topics 
Testing user authentication:
When you first go to the site and go to community board, you shouldn't be able to see anything unless you are logged in and will be redirected to the login page.
Testing create posts:
Create a post with all the data from the inputs, refresh page and see if new post shows …
> Be fixing login issue and testing community board

- server/routes/posts.js
updated some route with ensureAuth
check files of post route make sure all routes have ensureAuth
> Be ro quick updates ensure auth

- client/src/pages/Login.js
- client/src/pages/SignUp.js
There was no way for the user to know if they had logged in or signed up without errors, so I create a div on those pages for the errors to show if there is an error logging or signing up. 
Try to sign up with a password less than 8 characters
Try to login with an incorrect password on purpose, 
You should be able to see error messages in both instances
> shows errors to user if error occurs during signup or login

- client/src/components/AllPosts.js
- client/src/components/MessageBoardInteractive.js
- client/src/components/SocialButtons.js
- server/controllers/posts.js
- server/routes/main.js
connect DELETE  btn to the backend database and functionality
try and login and DELETE a post that you create and a post that was created by someone else
> Fe be setup delete btn

- client/src/components/AllPosts.js
- client/src/components/MessageBoardInteractive.js
- client/src/components/SocialButtons.js
- server/controllers/posts.js
- server/routes/main.js
connect like btn to the backend database and functionality
try and login and like a post
> Fe be setup like btn

- server/controllers/team.js
- server/models/Team.js
- server/routes/team.js
Added a Team member schema
change team routes for our team page access
review team schema and team routes
> updated schema for team members and adjusted routing

- client/src/components/AllPosts.js
- client/src/components/MessageBoardInteractive.js
- client/src/pages/Community.js
Fixed the Community Board page so that when a post is submitted it auto refreshed the post list to show the new post
Login and try and submit a post to the community board, you shouldn't need to refresh it should automagically appear below once submitted
> auto refresh for community posts

- client/src/components/AllPosts.js
- client/src/components/CommentBox.js
- client/src/components/CommentButtons.js
- client/src/pages/Community.js
- server/controllers/posts.js
- server/models/Post.js
updated schema for Posts and Comments
updated get request for posts to include comments 
updated FE to make the request for comment and to submit comments to the database
Run servers
log in
go to community board and make a post
comment on that post
refresh page and verify comment loads
comment on post that you did not create as well
> commenting and display of comments

- client/src/components/AllPosts.js
- client/src/components/CommentBox.js
- client/src/components/CommentButtons.js
what i did:
fixed community board
> fe-fix-community-board

- server/controllers/posts.js
Made it so that when a user creates a post, they can do so without an image needed, this was done on the backend, FE team needs conditional in the FE to only show img if img is available in the database 
Login and try and make a post without an image and try and delete that post.
> post without images and delete posts without images

- server/controllers/auth.js
- server/controllers/fridge.js
- server/controllers/profile.js
- server/controllers/team.js
- server/routes/fridge.js
- server/routes/main.js
- server/routes/profile.js
- server/server.js
Just some psuedo code for backend 
no need
> just some psuedo code for backend

- client/src/components/AllPosts.js
- client/src/components/CommentBox.js
- server/controllers/auth.js
- server/server.js
Made minor changes so that you don't have to manually refresh again to see updates to community board after you add, delete comment or delete a post
> BElocationreload

- client/src/App.css
- client/src/components/AllPosts.js
- client/src/components/CommentBox.js
- client/src/components/Hero.js
- client/src/components/MessageBoardInteractive.js
- client/src/pages/Login.js
- client/src/pages/SignUp.js
- server/controllers/auth.js
- Add location.reload() to login/signup
- Adjust community styling
- Change Hero.js to include pantries
> Login/signup reload, minor styling

- client/src/App.js
- client/src/components/AllPosts.js
- client/src/components/CommentBox.js
- client/src/components/CommentButtons.js
- client/src/components/ProtectedRoute.js
- client/src/pages/Login.js
- client/src/pages/SignUp.js
- server/controllers/posts.js
- server/routes/posts.js
- removed window.reload for commenting and replaced it with dynamic rendering on front end so that it wouldn't cause issues with authenticated 
- Hide community board behind sign in wall
- fixed issue with deleting comments that didn't remove comment id from post schema comment array 
- CARRIED FUNCTIONALITY ON MY FREAKING BACK 💅🏾 
https://github.com/Resilient-Labs/nourish/assets/81394397/70b3c1aa-cc08-4e4c-af0f-ffd04e941bb9
> FE - community wall, BE - Reload of comments without full page reload

- client/package-lock.json
- client/src/components/AllPosts.js
- client/src/components/CommentBox.js
- client/src/components/Fridge.js
- client/src/components/MessageBoardInteractive.js
- client/src/components/Navbar.js
> Development testing
